7902970: Script build.sh will fail if the default shell is dash
openjdk/jtreg pull request #12
Opened 2021-06-12 15:05 UTC by lgxbslgx

Hi all,

My local default shell is `dash`.

```
$ ls -al /bin/*sh*
-rwxr-xr-x 1 root root 1113504 Jun 7 2019 /bin/bash
-rwxr-xr-x 1 root root 121432 Jan 25 2018 /bin/dash
lrwxrwxrwx 1 root root 4 Sep 26 2020 /bin/rbash -> bash
lrwxrwxrwx 1 root root 4 Sep 26 2020 /bin/sh -> dash
lrwxrwxrwx 1 root root 4 Sep 26 2020 /bin/sh.distrib -> dash
lrwxrwxrwx 1 root root 7 Sep 18 2020 /bin/static-sh -> busybox
```

When I use the command `sh make/build.sh --help`, the build.sh will fail.
Because the `dash` doesn't support the variables such as `BASH_SOURCE`.

The successful command is `bash make/build.sh --help`, which uses `bash` explicitly
instead of the default shell `sh` implicitly.

This patch clarifies this situation in the README.
Thanks for taking the time to review.

Best Regards,
-- Guoxiong

2021-07-08 03:39 UTC, jonathan-gibbons requested changes

2021-07-08 03:39 UTC, jonathan-gibbons commented on README.md
> +
Suggest simplifying it to:

```
If your shell is not compatible with `bash`, you may need to invoke `bash` explicitly:

     % bash make/build.sh --jdk JDK-directory

```

2021-07-08 04:44 UTC, lgxbslgx commented on README.md
> +
Good idea. Revised just now.

2021-07-13 18:34 UTC, jonathan-gibbons approved these changes

2021-07-13 18:37 UTC, jonathan-gibbons commented
Hmmm, I didn't mean to close the PR; I was trying to mark a conversation as Resolved.

2021-07-14 02:10 UTC, lgxbslgx commented
@jonathan-gibbons Thanks for your review. Could I get your help to sponsor this patch?

/integrate

2021-07-14 02:59 UTC, jonathan-gibbons commented
/sponsor

2021-07-14 02:59 UTC, closed without merging