add simple test workflow
openjdk/jtreg pull request #16
Opened 2021-07-09 22:14 UTC by iignatev

Hi all,

could you please review this small patch that adds a simple github action workflow to build and test `jtreg` on `linux-x64`?

Thanks,
-- Igor

2021-07-09 23:22 UTC, jonathan-gibbons requested changes

2021-07-09 23:22 UTC, jonathan-gibbons commented on .github/workflows/test.yml
> +        run: sh make/build-all.sh ${JAVA_HOME_8_X64}
needs to be `make/build.sh`  

`make/build-all.sh` is obsolete and should now be deleted.

2021-07-09 23:22 UTC, jonathan-gibbons commented on .github/workflows/test.yml
> +             sh make/build-all.sh ${JAVA_HOME_8_X64}
use `make/build.sh`

2021-07-09 23:33 UTC, iignatev commented
@jonathan-gibbons , I've updated the workflow to use `make/build.sh` and also noticed that I used `JDK8_HOME` when it should have been `JDK8HOME`

2021-07-10 00:21 UTC, jonathan-gibbons approved these changes
Thanks for looking at this.

Looks generally OK; I'm not an expert on GitHub Actions, but it seems to satisfy the initial criteria of "do no harm" ;-)

Are other versions of JDK available for GitHub Actions?  Some of the tests are specific to versions of JDK ... and are guarded by `ifdef JDK`_N_`HOME` for a variety of values of _N_

2021-07-10 00:36 UTC, iignatev commented
Thanks, Jon.

> Are other versions of JDK available for GitHub Actions? ...

on linux, there are only JDK8 and JDK11 preinstalled, there are however no JDK11-specific tests (or at least there are no `ifdef JDK11HOME`). windows hosts have 8, 11, and 13; macos -- 8, [11;14]; I'm working on a patch to add testing on these platforms as well, but both have their own issues.

/integrate

2021-07-10 00:37 UTC, closed without merging