7903872: Option testThreadFactoryPath support relativepath
openjdk/jtreg pull request #233
Opened 2024-10-21 09:48 UTC by sendaoYan

Hi all,
Currently, the jtreg option `-testThreadFactoryPath` doesn't support relativepath.
I think jtreg can support relativepath for option `-testThreadFactoryPath`, same like to `-jdk` or `-nativepath`.
Risk is low.

2024-10-21 10:10 UTC, sormuras requested changes

2024-10-21 10:10 UTC, sormuras commented on src/share/classes/com/sun/javatest/regtest/config/RegressionParameters.java
> +        this.testThreadFactoryPath = new File(testThreadFactoryPath).getAbsolutePath();
Let's use NIO `Path` here.

```suggestion
        this.testThreadFactoryPath = Path.of(testThreadFactoryPath).toAbsolutePath().toString();
```

2024-10-21 10:36 UTC, sormuras commented
Do you know why the `void setTestThreadFactoryPath(String testThreadFactoryPath)` doesn't get a similar split/parsing treatment as `setTimeoutHandlerPath(String timeoutHandlerPath)` ?

https://github.com/openjdk/jtreg/blob/cf42c7c3cae4b7ef52378a1b24f94dfecd16e112/src/share/classes/com/sun/javatest/regtest/config/RegressionParameters.java#L1243-L1251

2024-10-21 14:40 UTC, sormuras commented
Thanks for the update to use NIO API.

Please also extend the existing test in https://github.com/openjdk/jtreg/tree/master/test/testThreadFactory to use both kinds of paths: one absolute path and one relative path.

2024-10-21 16:35 UTC, sendaoYan commented
> Please also extend the existing test in https://github.com/openjdk/jtreg/tree/master/test/testThreadFactory to use both kinds of paths: one absolute path and one relative path.

TestThreadFactoryRelativePath has been added for test the relative path. The test has been verified locally.
```
bash build/make.sh $(pwd)/build/test/TestThreadFactoryRelativePath.ok $(pwd)/build/test/TestThreadFactoryAbsolutePath.ok
find build/test/ -name "*.ok" | xargs cat
```

2024-10-22 02:14 UTC, sendaoYan commented
GHA report failure `gzip: stdin: not in gzip format` at `Installed distributions` stage, seems like github action issue.

2024-11-19 06:09 UTC, sendaoYan commented
/open

2024-11-20 11:08 UTC, sormuras approved these changes
Looks good to me.

2024-11-20 12:59 UTC, sendaoYan commented
Thanks all for the review.

The newly added tests and the existing tests run passed locally.

/integrate

2024-11-22 04:13 UTC, jaikiran commented
/sponsor

2024-11-22 04:13 UTC, closed without merging

2024-11-22 05:50 UTC, sendaoYan commented
Thanks for the sponsor.