CODETOOLS-7903883 --verify-exclude test existence and format checks are broken
openjdk/jtreg pull request #236
Opened 2024-11-13 09:11 UTC by LudwikJaniuk

2024-11-13 15:54 UTC, sormuras requested changes
Looks good so far, left some requests regarding a `TODO` comment and optional verbose output.

2024-11-13 15:54 UTC, sormuras commented on src/share/classes/com/sun/javatest/regtest/tool/Tool.java
> +
```suggestion
```

Please don't add `TODO` comments — just do it, or don't.

2024-11-13 15:54 UTC, sormuras commented on src/share/classes/com/sun/javatest/regtest/tool/Tool.java
> +            out.println(i18n.getString("main.tests.suite", ts.getRootDir()));
Guard this output line by the `--verbose` option?

2024-11-13 15:54 UTC, sormuras commented on src/share/classes/com/sun/javatest/regtest/tool/Tool.java
> -                out.println(tr.getTestName());
This print statement would now produce many output lines by default - perhaps, re-add and guard it via the `--verbose` flag?

2024-11-15 09:17 UTC, LudwikJaniuk commented
Thank you for reviewing @sormuras. I agree with all your comments and have addressed them. I chose to put the test names behing -va because that's a huuuuge list for the jdk.

2024-11-20 10:32 UTC, sormuras approved these changes
Looks good to me.

2024-12-16 13:42 UTC, jaikiran approved these changes
I don't have prior knowledge of this code, but reading through what's stated in the linked JBS issue and a brief look at this code, this change appears reasonable to me.

Please generate a jtreg build with this change and use it against the JDK mainline repo once, to make sure this works as expected and doesn't cause any unforeseen failures.

2024-12-16 13:45 UTC, jaikiran commented
While at it, I noticed in the linked JBS issue, that the current existing error message says:

> The fully qualified test must exists.

The "exists" should have been "exist". Could you update that error message (and related self reg tests) to fix that typo? If you want to do it in a separate PR, that's fine too.

2024-12-16 14:21 UTC, jaikiran approved these changes

2024-12-16 15:15 UTC, LudwikJaniuk commented
I've fixed the exists typo and also ran mainline `configure --with-jtreg=my/build; make test TEST=tier1` with no issues. Therefore integrating.

2024-12-16 15:15 UTC, LudwikJaniuk commented
/integrate

2024-12-16 15:16 UTC, closed without merging